### ISSUE TITLE
preserve original template in DataRow if possible, when DataRow is created from Template

### ISSUE THREAD

**Issue by StephanWald** [BasisHub/components#81]
```
use com.basiscomponents.db.DataRow

tpl$="NAME:C(10),VORNAME:C(20)"
dim X$:TPL$
x.name$="Fuhrmann"
x.vorname$="Georg"

dr! = DataRow.fromTemplate(tpl$,x$)
? dr!

rem can we have this the same as tpl$, as long as there have been no changes
rem that would lead to a change in the template????
? dr!.getTemplate()
? dr!.getString()
```

**Comment by DaAmore** [comment]
Just to understand it right.
If i create a DataRow from a template String, the String should be stored and retrievable by DataRow#getTemplate();
What should be the default behaviour if a DataRow is created otherwise? 
 - return null? 
 - throw an exception?
If changes are made to a DataRow which would impact the TemplateString should it be updated, cleared or stay in its initial state?

**Comment by StephanWald** [comment]
If the DataRow is created by a template, we want to preserve it (and use it in the getTemplate() and getString() methods) as long as the DataRow is not changed. As soon as the DataRow gets changed in a way that results in a different template (like a new field is added dynamically) we throw away the template we saved and fall back to the template we use now (which is created dynamically in the DataRow class). Same applies for a DataRow that has never been created using a given template.

IOW: as long as a programer uses a template to create the DataRow, and then does not change the DataRow, we want to give him the getString and getTemplate back exactly in the format that was provided upon creation.
